import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Canvas, useThree, useFrame } from "@react-three/fiber";
import { Loader, Stats } from "@react-three/drei";
import * as THREE from "three";
import gsap from "gsap";
import { useLenis } from "lenis/react";

import {
  SceneEngineContext,
  useSceneEngine,
} from "./scenes-v2/SceneEngineContext";
// The last JSON exported via the GUI's "Export Settings" button (see the
// "Export" folder built below) — bundled at build time, so overwriting this
// file (e.g. with a fresh export) changes the app's actual initial values,
// no code edits needed. Starts as `{controllers:{},folders:{}}`, a true
// no-op (see applyFolderSettings/root.load below, which just skip any key
// that isn't present) until it's replaced.
import sceneV2Settings from "./scenes-v2/scene-v2-settings.json";
import { createSceneEngine } from "./scenes-v2/engine";
import { useDebugGui } from "./scenes-v2/useDebugGui";
import { useSharedMaps } from "./scenes-v2/useSharedMaps";
import { useSwingCarousel, STEP_VH_FRACTION } from "./scenes-v2/swingCarousel";
import { registerNavSectionTarget } from "./utils/navSectionTargets";
import { scrollNavState } from "./utils/scrollNavState";
import { useSceneToProductHandoff } from "./scenes-v2/useSceneToProductHandoff";
import { useIsDesktop } from "./hooks/useIsDesktop";
import { usePreloader } from "./components/Preloader/PreloaderContext";
import HandoffFogWipe from "./scenes-v2/HandoffFogWipe";
import SteamOverlay from "./scenes-v2/SteamOverlay";
import ScenePrewarm from "./scenes-v2/ScenePrewarm";
import { shouldRunHeavyPasses } from "./scenes-v2/restGate";
import ProductSceneV2 from "./scenes-v2/product/ProductSceneV2";
import { useProductAssets } from "./scenes-v2/product/useProductAssets";
import ProductOverlayV2 from "./scenes-v2/product/ProductOverlayV2";
import HeroScrollCue from "./components/HeroScrollCue/HeroScrollCue";
import { useProductPhase } from "./scenes-v2/product/useProductPhase";
import { useProductAutoZoom } from "./scenes-v2/product/useProductAutoZoom";
import { SCROLL_LENGTH_VH as PRODUCT_RANGE_VH } from "./scenes-v2/product/constants";
import SceneOneV2 from "./scenes-v2/scenes/SceneOneV2";
import SceneFiveV2 from "./scenes-v2/scenes/SceneFiveV2";
import SceneTwoV2 from "./scenes-v2/scenes/SceneTwoV2";
import SceneThreeV2 from "./scenes-v2/scenes/SceneThreeV2";
import SceneFourV2 from "./scenes-v2/scenes/SceneFourV2";
import BottleRigV2, {
  BOTTLE_CENTER_OFFSET_Y,
  BOTTLE_OFFSET_Z,
} from "./scenes-v2/scenes/BottleRigV2";
import BottleStudioLights from "./scenes-v2/product/BottleStudioLights";
import SceneCaption from "./scenes-v2/SceneCaption";
import VideoPlaneV2 from "./scenes-v2/scenes/VideoPlaneV2";
import { DEFAULT_LIGHT_UP as LIGHT_UP_SHAPE } from "./scenes-v2/lightUpDefaults";
import homescene1Url from "./assets/seqs-1700/bathroom-1-c.mp4";
import homescene4Url from "./assets/seqs-1700/lover-loop-1.mp4";
import homescene4Intro from "./assets/seqs-1700/lover-intro-1.mp4";
// The rendered-clip reveal's assets (REVEAL_MODE.CLIPS below): a light-on
// intro rendered from the SAME setup as bathroom-1-c's loop — which is the
// whole point, since the two are joined by a hard cut — plus that intro
// reversed, generated by `npm run outros` (see scripts/make-outros.mjs).
import bathroom1cIntroUrl from "./assets/seqs-1700/bathroom-1-c-intro.mp4";
import bathroom1cOutroUrl from "./assets/seqs-1700/bathroom-1-c-outro.mp4";
// Scene Five's own loop + rendered intro/outro — a separate render from
// bathroom-1-c, so it needs its own matched pair (see the CLIPS comment
// below: clips only work seamlessly against the loop they were rendered
// against).
import homescene5Url from "./assets/seqs-1700/bathroom-5.mp4";
import bathroom5IntroUrl from "./assets/seqs-1700/bathroom-5-intro.mp4";
import bathroom5OutroUrl from "./assets/seqs-1700/bathroom-5-outro.mp4";
// Scene Two's own loop + rendered intro/outro — same reasoning as Scene
// Five's above, a separate render from bathroom-1-c/bathroom-4.
import homescene2Url from "./assets/seqs-1700/bathroom-2.mp4";
import bathroom2IntroUrl from "./assets/seqs-1700/bathroom-2-intro.mp4";
import bathroom2OutroUrl from "./assets/seqs-1700/bathroom-2-outro.mp4";
// Scene Three's (Dreamer's) own loop + rendered intro/outro — same reasoning
// as Scene Two/Five's above, a separate render from bathroom-1-c/bathroom-4.
import homescene3Url from "./assets/seqs-1700/dreamer-loop.mp4";
import bathroom3IntroUrl from "./assets/seqs-1700/dreamer-intro.mp4";
import bathroom3OutroUrl from "./assets/seqs-1700/dreamer-outro.mp4";
// import homeVideoUrl from "./assets/ranbir/home-video.mp4";
import "./Scene.v2.css";

// Flip to false to go back to mounting each scene's real 3D Component (see
// SCENES below) instead of a full-bleed looping video plane. Single switch,
// no per-scene bookkeeping — see SceneContents' render of SCENES.
const USE_VIDEO_PLACEHOLDERS = true;

// Persistent camera-facing steam veil (see SteamOverlay). Flip back on to
// remount it — the component, its fluid sim, and the GUI folder all stay.
const RENDER_STEAM_OVERLAY = false;

// Which way a scene's video plane reveals itself as it swings into view.
// Two entirely different mechanisms, one switch:
//
//   LIGHT — a "lights coming on" curve computed from the loop footage in the
//           shader (see VideoPlaneV2's LIGHT_UP_FRAGMENT). Needs no extra
//           assets and cannot mismatch, since there's no second clip: at rest
//           the gain is exactly 1.0, i.e. the untouched video. Tunable live
//           in the "Light Up" GUI folder.
//   CLIPS — the scene's own rendered intro/outro clips, HARD CUT in and out
//           with no cross-fade (see VideoPlaneV2's useClipReveal). Real light
//           physics — shadows, caustics and reflections resolve the way the
//           renderer says they should — but only seamless where the clips and
//           the loop come from the same render, since the join is a straight
//           jump from one file's frame to another's.
//
// Scenes with no `intro` authored fall back to LIGHT even in CLIPS mode, so
// this is safe to flip with only some of the set covered.
const REVEAL_MODE = {
  LIGHT: "light",
  CLIPS: "clips",
};
const ACTIVE_REVEAL = REVEAL_MODE.CLIPS;

// Each carousel scene from Scene.jsx, model + material setup only. Layout
// and scroll-driven motion live in useSwingCarousel (see swingCarousel.js):
// scenes One/Three and Two/Four each take turns through the SAME pair of
// front/back slots (index parity picks the pair — see its own comment),
// which is what "places" one-with-three and two-with-four together.
const SCENES = [
  // Rotation order: lover -> rebel -> sport -> dreamer -> sage. Slot-pairing
  // (see useSwingCarousel's "index parity" comment) is purely by array index,
  // not by id, so this order is free to change without touching the carousel
  // engine itself.
  {
    id: "four",
    label: "Scene Four",
    Component: SceneFourV2,
    bottlePersona: "lover",
    intro: homescene4Intro,
    videoUrl: homescene4Url,
    // No clips: nothing has been rendered against this loop, and a bathroom-1
    // intro cut into a bathroom-4 loop is exactly the mismatch CLIPS mode
    // exists to avoid. Falls back to the shader reveal.
  },
  {
    id: "five",
    label: "Scene Five",
    Component: SceneFiveV2,
    bottlePersona: "rebel",
    videoUrl: homescene5Url,
    intro: bathroom5IntroUrl,
    outro: bathroom5OutroUrl,
  },
  // Scene One and Three ship facing the opposite way from Two/Four on their
  // own authored Y axis — extraYRotation corrects that per-scene, layered on
  // top of the shared "face the front slot" rotation below. Default of PI
  // (180deg) is a starting point only — see DEFAULT_EXTRA_Y_ROTATIONS below,
  // it's GUI-tunable per scene at runtime, not fixed.
  {
    id: "one",
    label: "Scene One",
    Component: SceneOneV2,
    bottlePersona: "sport",
    // Placeholder video for this slot while USE_VIDEO_PLACEHOLDERS is on
    // (see VideoPlaneV2) — swap per scene by changing just this URL,
    // independent of every other scene's placeholder.
    videoUrl: homescene1Url,
    // Only used while ACTIVE_REVEAL is CLIPS, and only meaningful paired with
    // the loop they were rendered against (bathroom-1-c) — scenes on another
    // loop leave these off and get the shader reveal instead.
    intro: bathroom1cIntroUrl,
    outro: bathroom1cOutroUrl,
  },
  {
    id: "three",
    label: "Scene Three",
    Component: SceneThreeV2,
    bottlePersona: "dreamer",
    videoUrl: homescene3Url,
    intro: bathroom3IntroUrl,
    outro: bathroom3OutroUrl,
  },
  {
    id: "two",
    label: "Scene Two",
    Component: SceneTwoV2,
    bottlePersona: "sage",
    videoUrl: homescene2Url,
    intro: bathroom2IntroUrl,
    outro: bathroom2OutroUrl,
  },
];

// Exposed so callers (e.g. HomeV2Page) can key off "the last scene" without
// importing/duplicating the SCENES array.
export const SCENE_COUNT = SCENES.length;

// Ring-order scene ids, handed to BottleStudioLights so it can look up the
// front scene's own kicker tint (see studioSceneTints.js) from the same
// progressRef.frontIndex the carousel already maintains. Module-level so the
// array identity is stable across renders.
const SCENE_IDS = SCENES.map((s) => s.id);

// Product's room is no longer a ring slot — the carousel owns exactly
// SCENES.length steps (see useSwingCarousel's sceneCount/maxStep below).
// Reaching the last step and scrolling forward once more triggers a one-shot
// cinematic handoff (see useSceneToProductHandoff) instead of a swing: it
// fades the last plane out, fades product's room in, flies the carousel's
// own bottle onto its resting spot in the room, then auto-scrolls into
// useProductPhase's own continuous camera-flythrough scrub.
//
// HANDOFF_SCROLL_VH is the scroll distance (vh) that one-shot sequence's own
// auto-scroll (its final leg) advances the page by — carved out of the
// pinned section's total height the same way STICKY_RELEASE_VH is, see
// below and SceneV2's own scroll-section height calc.
const HANDOFF_SCROLL_VH = 90;

// `.scene-v2` is `position: sticky; top: 0` and one viewport tall, so it can
// only stay pinned while its containing section still has a viewport's worth
// of room left below — i.e. the section's LAST 100vh is the unstick/scroll-
// away phase, not usable pinned scroll. Every scroll range that expects the
// canvas to be held in place (the carousel's steps, then the product
// flythrough) has to fit in `height - 100vh`, so this is added on top of
// them rather than carved out of them. The original section's trailing
// "rest + buffer" 50vh pair was exactly this allowance under another name.
const STICKY_RELEASE_VH = 100;

// Product's own "face the front slot" correction, same role
// DEFAULT_EXTRA_Y_ROTATIONS plays for each SCENES entry. Unlike the scenes'
// video planes this does NOT decide how the room ends up framed — the
// alignment solve (see useProductAlignment) compensates for whatever this
// is set to, so the resting shot is identical either way. What it does
// change is the PATH the room takes swinging in: which way it rotates
// through as it comes round the ring. GUI-tunable ("Product V2 >
// Placement") for exactly that reason.
const DEFAULT_PRODUCT_RING_ROTATION_DEG = 180;

// See useProductAlignment's own comment — all-zero is the exact,
// fully-seamless solve with no manual correction. x/y/z are in the fixed
// camera's own local space (+x right, +y up, +z closer).
const DEFAULT_PRODUCT_NUDGE = { x: 0, y: 0, z: 10 };
const DEFAULT_PRODUCT_FINAL_NUDGE_Z = 20;

// Default per-scene extraYRotation (radians) — GUI-tunable at runtime, see
// SceneV2's `extraYRotations` state and its "Model Rotation" GUI folder.
const DEFAULT_EXTRA_Y_ROTATIONS = Object.fromEntries(
  SCENES.map((s) => [s.id, Math.PI]),
);

// "Lights coming on" reveal over each scene's video plane (see
// VideoPlaneV2's LIGHT_UP_FRAGMENT) — driven by how far the scene has swung
// in, so it needs no intro/outro clip and can't mismatch the loop it reveals.
// The shape of the curve comes from lightUpDefaults; everything here is
// GUI-tunable at runtime via the "Light Up" folder below.
// `preview`/`previewOn` are the debug pair only — see the "Light Up" GUI
// folder: they hand the FRONT scene's reveal over to a manual on/off toggle
// instead of the scroll, and are forced back off after settings load so an
// export taken mid-preview can't boot the app into a dark scene.
const DEFAULT_LIGHT_UP = {
  ...LIGHT_UP_SHAPE,
  preview: false,
  previewOn: false,
};

const CIRCLE_RADIUS = 7;

// This Canvas's ACES exposure — read by the <Canvas onCreated> below AND
// handed to the bottle's studio rig/materials, which were authored at
// /bottle-studio's own 0.2 and rescale themselves to hold that same look
// here (see scenes-v2/studioExposure.js). Two places, one number: they must
// never drift apart or the bottle re-blows out.
const CANVAS_EXPOSURE = 1.8;
// Angle (degrees) the outgoing/incoming scene sweep through per transition
// step — was a fixed 180° (FRONT/BACK exactly opposite); now GUI-tunable,
// see SceneV2's `sweepAngleDeg` state and the "Sweep Angle" GUI control,
// and useSwingCarousel's own module comment for how this drives the ring.
const DEFAULT_SWEEP_ANGLE_DEG = 80;

// How close (degrees, measured from FRONT) an incoming/outgoing scene has to
// swing before its baked lights start ramping — see swingCarousel.js's
// bakedLightProximity. Smaller = lights snap on later/closer to FRONT,
// larger = they start ramping earlier in the swing.
const DEFAULT_LIGHT_REVEAL_ANGLE_DEG = 20;

// Rotation each scene's own group needs, at rest in the FRONT slot, to face
// the (fixed) camera — see swingCarousel.js's module comment for the
// derivation. Index-aligned with SCENES. `extraYRotations` is keyed by
// scene id (radians), see DEFAULT_EXTRA_Y_ROTATIONS.
const getFaceRotations = (extraYRotations) =>
  SCENES.map((s) => Math.PI + (extraYRotations[s.id] ?? 0));

// "Resting" transform for each scene's group — index 0 at FRONT, everything
// else parked at BACK. Set directly as JSX props (not left to
// useSwingCarousel's own layout effect to apply) so every scene is in the
// right place from the very first paint, with no dependency on ref-attach
// timing inside react-three-fiber's own commit — a group left at the JSX
// default (the origin) would sit right where the fixed camera does, which
// reads as a black screen (camera embedded in unlit geometry), not an error.
const getRestFrame = (faceRotations, i) => {
  const angle = i === 0 ? 0 : Math.PI;
  const z = i === 0 ? -CIRCLE_RADIUS : CIRCLE_RADIUS;
  return { position: [0, 0, z], rotationY: faceRotations[i] - angle };
};

// The transform a slot ends up with once it has actually SWUNG to FRONT —
// i.e. what swingCarousel's own setGroupFrame produces at θ=0, which is not
// the same thing as getRestFrame above (that one parks every non-zero index
// at BACK for the initial paint). Reproduced here rather than imported
// because the alignment solve (see useProductAlignment) has to know this
// pose up front, before product has ever swung anywhere.
const getFrontRestFrame = (faceRotations, i) => {
  const x = 0;
  const z = -CIRCLE_RADIUS;
  const camX = DEFAULT_CAMERA.position[0];
  const camZ = DEFAULT_CAMERA.position[2];
  return {
    position: [x, 0, z],
    rotationY: Math.atan2(camX - x, camZ - z) + faceRotations[i],
  };
};

// The camera's resting pose — aimed at the FRONT slot (0,0,-CIRCLE_RADIUS),
// same standoff the Focus buttons use. NOT (0,0,0): with the camera only
// 1.5 up and 0.01 forward of the origin, "look at the origin" is nearly
// straight down (the Y offset dwarfs the 0.01 Z offset) — camera pointed at
// empty ground next to its own feet, nowhere near scene one out at z=-16.
// That's the black screen: solid background color, nothing wrong, camera
// just never aimed at any scene to begin with.
const DEFAULT_CAMERA = {
  position: [0, 0.2, -CIRCLE_RADIUS + 6],
  // -11.6
  target: [0, 0, -CIRCLE_RADIUS],
};

// Debug-only geometry (minimap ring, main-camera frustum, per-scene markers)
// lives on its own render layer so it's visible to the minimap's debug
// camera but invisible to the main camera (which only has layer 0 enabled
// by default) — no per-object visibility toggling needed.
const DEBUG_LAYER = 31;
const DEBUG_COLORS = ["#ff4d4d", "#c04dff", "#4ddc4d", "#4d8dff", "#ffd24d"]; // index-aligned with SCENES
const MINIMAP_SIZE = 400;
const MINIMAP_PAD = 20;

const setDebugLayer = (obj) => obj?.layers.set(DEBUG_LAYER);

// Wireframe circle on the XZ plane at the carousel's radius — the swing
// carousel's whole path — so the minimap reads as a literal top-down map of
// where FRONT/BACK are and how far along it each scene currently is.
function DebugRing({ radius }) {
  const geometry = useMemo(() => {
    const points = [];
    const segments = 64;
    for (let i = 0; i <= segments; i++) {
      const a = (i / segments) * Math.PI * 2;
      points.push(
        new THREE.Vector3(Math.sin(a) * radius, 0, Math.cos(a) * radius),
      );
    }
    return new THREE.BufferGeometry().setFromPoints(points);
  }, [radius]);

  return (
    <line ref={setDebugLayer} geometry={geometry}>
      <lineBasicMaterial color="#555555" />
    </line>
  );
}

// Visualizes the main (fixed) camera's own frustum — position, aim, and FOV
// — from the minimap's outside vantage point. Updated every frame since
// CameraRig tweens the real camera continuously.
function MainCameraHelper({ camera }) {
  const helper = useMemo(() => {
    const h = new THREE.CameraHelper(camera);
    setDebugLayer(h);
    return h;
  }, [camera]);

  useEffect(() => () => helper.dispose(), [helper]);
  useFrame(() => helper.update());

  return <primitive object={helper} />;
}

// SceneLights (per-scene hemi+directional, fading with the carousel) and
// BottleLights (the bottle's always-on 3-point rig) both used to live here —
// replaced by BottleStudioLights (the Bottle.blend-derived studio rig, see
// that file), mounted once below alongside BottleRigV2. Scene Four's glass
// panels, which SceneLights used to also light, currently have no dedicated
// light source as a result.

// Cursor parallax — TRUCKs the camera: translates position AND lookAt
// target by the identical offset, never just position, so the view
// direction stays constant. That's what keeps it symmetric left/right for
// every scene regardless of where its model sits; re-aiming at a fixed
// pivot instead (moving position but not target) turns the same
// translation into a slight orbit around that pivot, asymmetric for
// anything off-center (mirrors the original Scene.jsx's own fix for this,
// see its "Cursor parallax" comment).
//
// Driven entirely by gsap (one retargeted tween, same "kill + restart from
// wherever it currently is" trick swingCarousel.js uses for its own tween)
// instead of a hand-rolled per-frame low-pass. That low-pass needed a slow
// ease factor to look smooth at all, which is what read as sluggish/laggy
// cursor-follow — a proper eased tween gets a smooth, non-linear settle
// without needing to run every render frame at all: gsap's own ticker
// drives it, and onUpdate below is the only thing touching the camera.
const PARALLAX_STRENGTH_X = 0.06; // fraction of camera->target distance at full mouse X
const PARALLAX_STRENGTH_Y = 0.02; // fraction of camera->target distance at full mouse Y
const PARALLAX_DURATION = 0.5;
const PARALLAX_EASE = "power2.out";

// Camera stays fixed for the real experience (the swing carousel moves the
// scenes, not the camera — see swingCarousel.js) — no OrbitControls. Its
// own per-frame update() was fighting any camera.position we set directly
// (it recomputes position from its own internal spherical every frame,
// unaware of external writes), and the wheel it binds for zoom by default
// would also contend with the carousel's own wheel handling.
function CameraRig({ fov, debugPosition, parallaxEnabled }) {
  const { camera } = useThree();
  // The camera's resting pose, ABSENT cursor parallax — gsap/debug writes
  // land here, never on camera.position directly, so the parallax tween's
  // own onUpdate (which recomputes camera.position/lookAt from this base)
  // can never fight the base's own in-flight tween.
  const basePosition = useRef(new THREE.Vector3(...DEFAULT_CAMERA.position));
  const lookTarget = useRef(new THREE.Vector3(...DEFAULT_CAMERA.target));
  const parallax = useRef({ x: 0, y: 0 });
  const parallaxTweenRef = useRef(null);
  // Mirrors the `parallaxEnabled` prop into a ref so the mount-only
  // mousemove effect below (empty deps — it must not re-bind the listener
  // on every toggle) can still read the latest flag on each event.
  const parallaxEnabledRef = useRef(parallaxEnabled);
  parallaxEnabledRef.current = parallaxEnabled;

  // Single source of truth for what actually lands on the camera — called
  // from every tween's onUpdate (base position/target AND parallax) so
  // whichever is animating always composes with the other's latest value,
  // never a stale one.
  const applyCamera = () => {
    camera.position.set(
      basePosition.current.x + parallax.current.x,
      basePosition.current.y + parallax.current.y,
      basePosition.current.z,
    );
    camera.lookAt(
      lookTarget.current.x + parallax.current.x,
      lookTarget.current.y + parallax.current.y,
      lookTarget.current.z,
    );
  };

  useEffect(() => {
    const handleMove = (event) => {
      if (!parallaxEnabledRef.current) return;
      const mouseX = (event.clientX / window.innerWidth) * 2 - 1;
      const mouseY = (event.clientY / window.innerHeight) * 2 - 1;
      const dist = basePosition.current.distanceTo(lookTarget.current) || 1;
      parallaxTweenRef.current?.kill();
      parallaxTweenRef.current = gsap.to(parallax.current, {
        x: mouseX * dist * PARALLAX_STRENGTH_X,
        y: -mouseY * dist * PARALLAX_STRENGTH_Y, // CSS Y down -> camera Y up when cursor rises
        duration: PARALLAX_DURATION,
        ease: PARALLAX_EASE,
        onUpdate: applyCamera,
      });
    };
    window.addEventListener("mousemove", handleMove, { passive: true });
    return () => window.removeEventListener("mousemove", handleMove);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Flipping the GUI toggle off mid-offset shouldn't leave the camera
  // stuck mid-truck — ease the existing offset back to dead center instead
  // of snapping, same duration/ease as a live parallax retarget.
  useEffect(() => {
    if (parallaxEnabled) return;
    parallaxTweenRef.current?.kill();
    parallaxTweenRef.current = gsap.to(parallax.current, {
      x: 0,
      y: 0,
      duration: PARALLAX_DURATION,
      ease: PARALLAX_EASE,
      onUpdate: applyCamera,
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [parallaxEnabled]);

  useEffect(() => {
    camera.position.copy(basePosition.current);
    camera.lookAt(lookTarget.current); // orient correctly before the tween's own first tick
    gsap.to(basePosition.current, {
      x: DEFAULT_CAMERA.position[0],
      y: DEFAULT_CAMERA.position[1],
      z: DEFAULT_CAMERA.position[2],
      duration: 1.1,
      ease: "power3.inOut",
      onUpdate: applyCamera,
    });
    gsap.to(lookTarget.current, {
      x: DEFAULT_CAMERA.target[0],
      y: DEFAULT_CAMERA.target[1],
      z: DEFAULT_CAMERA.target[2],
      duration: 1.1,
      ease: "power3.inOut",
      onUpdate: applyCamera,
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [camera]);

  useEffect(() => {
    camera.fov = fov;
    camera.updateProjectionMatrix();
  }, [fov, camera]);

  // Debug GUI position override — kills any in-flight focus/center tween so
  // it can't immediately overwrite the manually-dialed-in position, sets the
  // BASE directly (no easing; this is for precise placement, not motion) —
  // applyCamera still layers whatever cursor parallax is currently active
  // on top of it.
  useEffect(() => {
    if (!debugPosition) return;
    gsap.killTweensOf(basePosition.current);
    basePosition.current.set(debugPosition.x, debugPosition.y, debugPosition.z);
    applyCamera();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [debugPosition]);

  return null;
}

// Static top-down "map" camera for the minimap inset — square aspect (it
// always renders into a fixed 400x400 viewport, see PostFXV2), parked high
// above the origin looking straight down the Y axis. up is forced to -Z
// (instead of the default +Y, which is degenerate for a straight-down look)
// so world -Z (the FRONT slot) reads as "up" on screen, matching the ring's
// own θ=0-at-FRONT convention.
function useMinimapCamera(radius) {
  return useMemo(() => {
    const cam = new THREE.PerspectiveCamera(55, 1, 0.1, 1000);
    cam.up.set(0, 0, -1);
    cam.position.set(0, radius * 3, 0.01);
    cam.lookAt(0, 0, 0);
    cam.layers.enable(DEBUG_LAYER);
    return cam;
  }, [radius]);
}

// progressRef.frontIndex is written every frame (see swingCarousel.js) but
// lives outside React state — this is the bridge that lets the DOM caption
// overlay (rendered outside the Canvas, in plain HTML) react to it, without
// re-rendering anything inside the Canvas on every frame: only calls
// `onChange` the instant frontIndex actually flips to a new scene.
function ActiveSceneTracker({ progressRef, onChange }) {
  const lastRef = useRef(-1);
  useFrame(() => {
    const idx = progressRef.current.frontIndex;
    if (idx !== lastRef.current) {
      lastRef.current = idx;
      onChange(idx);
    }
  });
  return null;
}

// Replaces PostFXV2 (deleted — see this file's own "no postprocessing" note,
// matching BottleStudioPage.jsx's setup: plain Canvas render, no
// EffectComposer/bloom/SMAA). PostFXV2 was never JUST a bloom pass though —
// it was also the thing that took over this Canvas's render loop entirely
// (a `useFrame` with a priority arg switches R3F to manual rendering) and,
// bundled into that same per-frame call, ticked `engine.update()` — the one
// thing that actually drives every animated shader material (fog/sea-wave/
// droplet, see materials.js) and refreshes water reflection render targets
// across all 5 scenes. Deleting PostFXV2 outright, with nothing replacing
// its render loop, would have silently frozen all of that along with the
// bloom it was actually meant to remove. This keeps exactly the render-loop
// and engine-tick duties, drops the composer/bloom/SMAA pipeline.
function SceneRenderDriver({
  progressRef,
  productActiveRef,
  productRevealed,
  handoffActiveRef,
  minimapEnabled,
  minimapCamera,
}) {
  const { gl, scene, camera, size } = useThree();
  const { engine } = useSceneEngine();
  const [clock] = useState(() => new THREE.Clock());

  useFrame(() => {
    // Product's own flythrough (see SelectiveBlurRenderer) owns the frame
    // once scroll has carried past the carousel's own range — see
    // useProductPhase. Two priority-1 useFrame renderers sharing one canvas
    // would otherwise both draw to the same default framebuffer every
    // frame, wasting the GPU work of whichever drew first.
    if (productActiveRef?.current && productRevealed) return;

    engine.update(gl, scene, camera, clock.getElapsedTime(), {
      updateReflections: shouldRunHeavyPasses({
        progressRef,
        handoffActiveRef,
      }),
    });
    gl.render(scene, camera);

    // Debug picture-in-picture: a second, uncomposited render from the
    // minimap's own top-down camera into a scissored bottom-left square —
    // see PostFXV2's own comment on why scissor/viewport must be reset
    // after, or the next frame inherits the leftover rect.
    if (minimapEnabled && minimapCamera) {
      gl.setScissorTest(true);
      gl.setViewport(MINIMAP_PAD, MINIMAP_PAD, MINIMAP_SIZE, MINIMAP_SIZE);
      gl.setScissor(MINIMAP_PAD, MINIMAP_PAD, MINIMAP_SIZE, MINIMAP_SIZE);
      gl.clear(true, true, false);
      gl.render(scene, minimapCamera);
      gl.setScissorTest(false);
      gl.setViewport(0, 0, size.width, size.height);
    }
  }, 1);

  return null;
}

// Hides its children for as long as `hiddenRef` reads true. Driven per-frame
// off a ref rather than a React prop because the thing it tracks (product's
// scroll phase) changes mid-scroll and must not re-render the Canvas tree to
// do it — same reasoning as ActiveSceneTracker above.
function HideWhile({ hiddenRef, children }) {
  const ref = useRef(null);
  useFrame(() => {
    const group = ref.current;
    if (group) group.visible = !hiddenRef.current;
  });
  return <group ref={ref}>{children}</group>;
}

// Pumps a few on-demand renders so materials/water targets/the bloom
// composer all compile while the section is still off screen — the whole
// point of nearViewport's 100% rootMargin. Previously that warm-up window
// ran `frameloop="always"`, i.e. the FULL carousel (5 scenes, water
// reflection passes, N8AO, bloom) rendered at 60fps for a full viewport
// either side of the section. At scroll 0 that band already covers this
// section (it starts 60dvh below the fold), so the intro hero was animating
// its title against a saturated GPU — the Safari stutter. A handful of
// demanded frames compiles exactly the same programs without the loop.
function WarmupFrames({ active }) {
  const invalidate = useThree((state) => state.invalidate);
  useEffect(() => {
    if (!active) return undefined;
    let frames = 0;
    let raf = requestAnimationFrame(function pump() {
      invalidate();
      frames += 1;
      if (frames < 3) raf = requestAnimationFrame(pump);
    });
    return () => cancelAnimationFrame(raf);
  }, [active, invalidate]);
  return null;
}

function SceneContents({
  enabled,
  sectionInView,
  sectionRef,
  fov,
  transitionFov,
  minimapEnabled,
  debugCameraPosition,
  parallaxEnabled,
  extraYRotations,
  sweepAngle,
  lightRevealAngle,
  onActiveSceneChange,
  lenis,
  lightUp,
  productGui,
  productFacing,
  productNudge,
  productFinalNudgeZ,
  productRevealed,
  onProductRevealedChange,
  onProductActiveChange,
  productEnabled,
}) {
  const sharedMaps = useSharedMaps(!USE_VIDEO_PLACEHOLDERS);
  const { camera } = useThree();
  const { engine } = useSceneEngine();
  // Product's own pieces (ProductLights/useBottleReveal/SelectiveBlurRenderer)
  // read `gui` off SceneEngineContext just like every carousel scene does —
  // this nested provider is what points THEM at the separate "Product V2"
  // folder (see the outer SceneV2's own gui-building effect) instead of the
  // carousel's "Scene V2" one they'd otherwise inherit.
  const productContextValue = useMemo(
    () => ({ engine, gui: productGui, settings: null }),
    [engine, productGui],
  );
  // Index-aligned with SCENES only — product is no longer a ring slot (see
  // HANDOFF_SCROLL_VH's own comment), so these are back to their pre-product
  // size.
  const groupRefs = useRef(
    Array.from({ length: SCENES.length }, () => ({ current: null })),
  );
  const bakedLightRefs = useRef(
    Array.from({ length: SCENES.length }, () => ({ current: [] })),
  );
  const faceRotations = useMemo(
    () => getFaceRotations(extraYRotations),
    [extraYRotations],
  );
  const maxStep = SCENES.length - 1;

  // Product's own assets/alignment group, lifted up here (rather than owned
  // inside ProductSceneV2) so useSceneToProductHandoff below can read the
  // same assetsRef/alignRef ProductSceneV2 renders from — see
  // useProductAssets.js and ProductSceneV2's own comment.
  const { assetsRef: productAssetsRef, ready: productReady } =
    useProductAssets(productEnabled);
  const alignRef = useRef(null);
  // The carousel's own bottle rig's live THREE.Group + the handoff's flight
  // override — see BottleRigV2's own comment for how these two combine to
  // let an external gsap tween drive its transform without fighting its
  // normal per-frame math.
  const bottleGroupRef = useRef(null);
  const flightOverrideRef = useRef({
    active: false,
    hidden: false,
    position: new THREE.Vector3(),
    quaternion: new THREE.Quaternion(),
    scale: new THREE.Vector3(1, 1, 1),
    // Written every frame by BottleRigV2 with its OWN live resting pose (see
    // its useFrame) — the reverse handoff flight reads these as its landing
    // target so it aims at where the rig actually wants the bottle right now,
    // cursor tilt and carousel step included, rather than a stale snapshot.
    restPosition: new THREE.Vector3(),
    restQuaternion: new THREE.Quaternion(),
    // The currently-visible flavor mesh's own local scale (BOTTLE_SCALE, or
    // whatever the rig's GUI "Scale" slider currently has it at), published
    // live so the handoff can convert a target's WORLD scale into the
    // correct GROUP-local scale without hardcoding/duplicating that number.
    restChildScale: new THREE.Vector3(1, 1, 1),
  });
  // Filled in by scene "four"'s own <VideoPlaneV2> once its material exists
  // (see the onMaterialReady prop passed to it below) — the handoff fades
  // THIS material's opacity out.
  const sceneFourMaterialRef = useRef(null);
  // Gates ProductLights' real THREE.Light objects on/off — see
  // ProductSceneV2's own comment on why this can't just be `productRoomVisible`
  // (lights aren't scoped by mount/opacity the way meshes are, so turning
  // them on while scene "four" is still resting on screen blows it out).
  // Flipped true by useSceneToProductHandoff itself, exactly when the room
  // actually starts revealing.
  const lightsActiveRef = useRef(false);
  // Camera-facing fog plane (see HandoffFogWipe) that conceals the whole
  // scene-to-product swap — { opacity, mesh }, owned by
  // useSceneToProductHandoff's own gsap timeline.
  const handoffFogRef = useRef({ opacity: 0, mesh: null });
  // Whether the cloud wipe has actually swapped product's room IN yet —
  // flipped by useSceneToProductHandoff's timeline at the instant-swap point
  // of each direction, i.e. while the wipe fully covers the frame. This is
  // useProductAutoZoom's cue to start its single zoom-in tween, so that
  // motion is already underway as the fog parts (see both hooks' comments;
  // it replaces an earlier `revealSettleRef` tween that ran as a SEPARATE
  // motion and stopped dead before the zoom began, which read as a pause).
  const roomRevealedRef = useRef(false);
  // Whether product's own shower-fog plane (see ProductSceneV2) should be
  // showing. Flipped by useSceneToProductHandoff's timeline at the exact
  // instant-swap point in EACH direction — i.e. while the wipe fully covers
  // the frame — rather than derived by ProductSceneV2 from lightsActiveRef
  // or the wipe's own opacity: both of those flip at TRIGGER time, before
  // the clouds have arrived, which had the fog appearing late on the way in
  // and vanishing early on the way out.
  const showerFogRef = useRef({ revealed: false });

  // Where the product flythrough's own scrub picks up: right after the
  // carousel's OWN range PLUS the one-shot handoff sequence's own auto-scroll
  // distance (see HANDOFF_SCROLL_VH and useSceneToProductHandoff's leg E) —
  // no extra dead zone beyond that (see the scroll-section's own height
  // below). Read ahead of useSceneToProductHandoff itself: `activeRef`'s own
  // true->false edge (scrolling back UP out of product's range) is exactly
  // what that hook watches to fire the reverse handoff.
  // `activeRef` here is left as the raw, scroll-position-derived signal —
  // still what gates rendering (PostFXV2/ProductSceneV2), hotspot
  // eligibility, and the carousel bottle rig's visibility below. Its own
  // `phaseRef` is no longer used: useProductAutoZoom (below) replaces
  // scroll-scrubbing of the flythrough with an automatic play-through, and
  // writes its OWN phaseRef instead — see that hook's own comment.
  const { activeRef: productActiveRef } = useProductPhase({
    sectionRef,
    // Unreachable when product is switched off (see SceneV2's own
    // `productEnabled`) — the section has no product range to scroll into,
    // so this must never read true no matter how far the page scrolls.
    carouselOwnedVh: productEnabled
      ? maxStep * STEP_VH_FRACTION * 100 + HANDOFF_SCROLL_VH
      : Number.POSITIVE_INFINITY,
  });

  const {
    trigger: triggerHandoff,
    triggerReverse: triggerProductReverse,
    enterInstant: enterProductInstant,
    exitInstant: exitProductInstant,
    activeRef: handoffActiveRef,
  } = useSceneToProductHandoff({
    sectionRef,
    lenis,
    maxStep,
    assetsRef: productAssetsRef,
    ready: productReady,
    flightOverrideRef,
    sceneFourMaterialRef,
    lightsActiveRef,
    fogRef: handoffFogRef,
    roomRevealedRef,
    showerFogRef,
    productActiveRef,
    onProductActiveChange,
    handoffScrollVh: HANDOFF_SCROLL_VH,
  });

  // `productOnScreenRef` is what everything downstream gates on — see
  // useProductAutoZoom's own comment for why the raw scroll comparison
  // (`productActiveRef`) can't be used directly: it reads false at the exact
  // moment the forward transition lands, which suppressed both the zoom and
  // the "+" hotspots until a manual scroll nudge. The RAW ref is still
  // handed to useSceneToProductHandoff above, deliberately: its reverse
  // watcher fires on that ref's true->false edge, which the OR'd version
  // could never produce (it stays true for the whole reverse).
  const {
    phaseRef: productPhaseRef,
    onScreenRef: productOnScreenRef,
    landInstant: landProductInstant,
  } = useProductAutoZoom({
    revealedRef: roomRevealedRef,
    scrollActiveRef: productActiveRef,
    lenis,
    triggerReverse: triggerProductReverse,
  });

  const {
    visibleIndices,
    progressRef,
    syncToScroll: syncCarouselToScroll,
  } = useSwingCarousel({
    sectionRef,
    groupRefs: groupRefs.current,
    faceRotations,
    radius: CIRCLE_RADIUS,
    sceneCount: SCENES.length,
    camera,
    bakedLightRefs: bakedLightRefs.current,
    sweepAngle,
    lightRevealAngle,
    // The carousel drives camera.fov directly during a transition (see its
    // applyTransitionFov) — `fov` here is the resting value it returns to,
    // the same one CameraRig sets, so the two can't fight: CameraRig only
    // ever writes it on an actual GUI change, and every transition both
    // starts and ends at it.
    baseFov: fov,
    transitionFov,
    fovReturnAt: TRANSITION_FOV_RETURN_AT,
    lenis,
    // With product off there is nothing past the last scene to hand off TO,
    // so leave this unset: swingCarousel then falls through to its plain
    // releaseScroll() at that edge (see its own onForwardEdge comment) and
    // scrolling on from the last slide simply carries down the page — which
    // is what lets the page's own cloud transition take the seam instead.
    onForwardEdge: productEnabled ? triggerHandoff : undefined,
    disabledRef: handoffActiveRef,
  });
  const minimapCamera = useMinimapCamera(CIRCLE_RADIUS);

  // --- PageProgress rail targets -------------------------------------------
  //
  // Both live in the SAME pinned section, so neither is reachable by scroll
  // position alone: `.scene-v2` is sticky, and what is on screen at a given
  // offset inside it is decided by the carousel's own `stepRef` and by
  // whether product's room has been swapped in — not by the offset. See
  // utils/navSectionTargets.js. Everything below runs under
  // NavCloudTransition's full cover, so the swaps are never seen.
  const scrollPageTo = useCallback(
    (y) => {
      if (lenis) lenis.scrollTo(y, { immediate: true, force: true });
      else window.scrollTo(0, y);
    },
    [lenis],
  );

  const sectionTopPx = useCallback(() => {
    const el = sectionRef.current;
    return el
      ? el.getBoundingClientRect().top + window.scrollY
      : window.scrollY;
  }, [sectionRef]);

  useEffect(() => {
    const unregisterWorlds = registerNavSectionTarget("worlds", {
      // Scene One resting at FRONT, i.e. the very top of the carousel's own
      // range. The seam latch has to be disarmed too: this offset coincides
      // with CloudTransition's boundary marker, so landing here with it still
      // armed means the next downward tick replays the whole Seawave wipe.
      enter: () => {
        scrollPageTo(sectionTopPx());
        syncCarouselToScroll();
        scrollNavState.syncSeamAfterJump?.(false);
        return true;
      },
    });

    // No product range to jump to when it's switched off — leaving this
    // registered would give the rail a "Shop" target that lands the page
    // somewhere the section no longer extends to.
    const unregisterShop = !productEnabled
      ? () => {}
      : registerNavSectionTarget("shop", {
          // The finished product display, hotspots up and clickable — the state
          // the authored transition reaches after its fog wipe AND its 3.4s
          // camera zoom. Both are skipped rather than replayed: the nav clouds
          // already cover the swap, and a rail click shouldn't cost ~6s of
          // animation to arrive somewhere the label named directly.
          enter: () => {
            const vh = window.innerHeight / 100;
            const landingY =
              sectionTopPx() +
              (maxStep * STEP_VH_FRACTION * 100 + HANDOFF_SCROLL_VH) * vh;
            // Park the carousel on its last step FIRST: that is the step the
            // forward handoff is entered from, so it is what must be underneath
            // if the user later scrolls back out of product.
            scrollPageTo(landingY);
            syncCarouselToScroll();
            // Assets may still be loading — fall back to the plain scroll above
            // rather than half-entering a room that has no geometry yet.
            if (!enterProductInstant()) return false;
            landProductInstant();
            scrollNavState.syncSeamAfterJump?.(false);
            return true;
          },
          leave: exitProductInstant,
        });

    return () => {
      unregisterWorlds();
      unregisterShop();
    };
  }, [
    scrollPageTo,
    sectionTopPx,
    syncCarouselToScroll,
    enterProductInstant,
    exitProductInstant,
    landProductInstant,
    maxStep,
    productEnabled,
  ]);

  // Mounts product's room/bottle geometry once the carousel has actually
  // reached its last scene (see ProductSceneV2's own comment on `roomVisible`)
  // — stays true for the rest of the session once set, since nothing past
  // the last step can move visibleIndices again.
  const productRoomVisible = productEnabled && visibleIndices.has(maxStep);

  // Product's static resting placement — no longer ring-derived (it's not
  // swung into place, see useSceneToProductHandoff), just a fixed pose in
  // front of the same fixed camera every carousel scene rests at. Reuses
  // getFrontRestFrame with a synthetic single-entry faceRotations array,
  // since that helper only ever reads faceRotations[i].
  const productFrontRest = useMemo(
    () => getFrontRestFrame([Math.PI + productFacing], 0),
    [productFacing],
  );

  return (
    <>
      <CameraRig
        fov={fov}
        debugPosition={debugCameraPosition}
        parallaxEnabled={parallaxEnabled}
      />
      {/* Pays the GPU's first-draw cost (shader compiles + texture uploads)
          in the background — see ScenePrewarm's own comment. Mounted here so
          it sits inside the same Canvas whose renderer/scene it warms.
          No longer holds PreloaderV2: the overlay is the intro hero, and
          this work finishes during that reel / the scroll down to here. */}
      <ScenePrewarm
        assetsRef={productAssetsRef}
        // `productReady` never flips when the product path is switched off
        // (useProductAssets skips the whole load, by design). Warmup still
        // compiles the carousel's own materials immediately in that case.
        ready={productEnabled ? productReady : true}
      />
      <HandoffFogWipe opacityRef={handoffFogRef} />
      {RENDER_STEAM_OVERLAY && (
        <SteamOverlay
          progressRef={progressRef}
          handoffActiveRef={handoffActiveRef}
        />
      )}
      <ActiveSceneTracker
        progressRef={progressRef}
        onChange={onActiveSceneChange}
      />
      {SCENES.map((scene, i) => {
        const Comp = scene.Component;
        // sectionInView is a tight IO (not the 100% rootMargin that keeps
        // the Canvas frameloop warm). Without it, FRONT's loop keeps
        // decoding at the hero and the footer — visibility:hidden /
        // frameloop="never" does not pause <video>.
        const visible =
          enabled[scene.id] && visibleIndices.has(i) && sectionInView;
        const rest = getRestFrame(faceRotations, i);
        return (
          <group
            key={scene.id}
            ref={groupRefs.current[i]}
            position={rest.position}
            rotation={[0, rest.rotationY, 0]}
          >
            {USE_VIDEO_PLACEHOLDERS ? (
              <VideoPlaneV2
                visible={visible}
                videoUrl={scene.videoUrl}
                // Passing these is what selects the clip reveal — see
                // VideoPlaneV2's own comment. In LIGHT mode they never
                // arrive, so no clip <video> elements are created at all.
                introUrl={
                  ACTIVE_REVEAL === REVEAL_MODE.CLIPS ? scene.intro : undefined
                }
                outroUrl={
                  ACTIVE_REVEAL === REVEAL_MODE.CLIPS ? scene.outro : undefined
                }
                // Both needed so the plane can work out how far THIS scene
                // currently is from FRONT and drive its own light-up reveal
                // from that — read per-frame off the ref, so nothing here
                // re-renders.
                sceneIndex={i}
                // Index 0 is the one scene getRestFrame parks at FRONT for
                // the very first paint (see that function above) — i.e. the
                // only video the user is actually looking at the instant
                // this section reveals. See VideoPlaneV2's own comment: it
                // still gets fetch priority over the other four scenes'
                // files, but no longer holds PreloaderV2 (the intro hero
                // is on screen first; this clip has that whole reel + a
                // scroll to finish fetching).
                isInitialScene={i === 0}
                progressRef={progressRef}
                lightUp={lightUp}
                // Only scene "four" (the last one) needs its material
                // reachable — that's the one useSceneToProductHandoff fades
                // out. Every other scene gets undefined, a no-op.
                onMaterialReady={
                  scene.id === "four"
                    ? (m) => {
                        sceneFourMaterialRef.current = m;
                      }
                    : undefined
                }
              />
            ) : (
              <Comp
                visible={visible}
                sharedMaps={sharedMaps}
                // No postprocessing any more (see SceneRenderDriver) — a
                // scene's own optional selective-bloom object-layer setup
                // (e.g. Scene Three/Four) has nothing to opt into.
                postFxEnabled={false}
                lightsRef={bakedLightRefs.current[i]}
              />
            )}
            {/* Debug-only marker (see DEBUG_LAYER) — always present so the
                minimap shows all four slots moving, independent of which
                scene is actually toggled on/visible right now. */}
            <mesh position={[0, 4, 0]} ref={setDebugLayer}>
              <sphereGeometry args={[0.6, 12, 12]} />
              <meshBasicMaterial color={DEBUG_COLORS[i]} />
            </mesh>
          </group>
        );
      })}
      {/* Product's own group — no longer swung into place (see
          useSceneToProductHandoff), just a plain sibling parked at its own
          static resting pose in front of the same fixed camera every
          carousel scene rests at. Where the room sits INSIDE that group is
          still solved for (see useProductAlignment, handed the front-rest
          pose below): it's placed so the flythrough's own frame-0 camera
          pose coincides exactly with the carousel's resting camera pose —
          what makes the eventual camera switch seamless. */}
      {productEnabled && (
        <group
          position={productFrontRest.position}
          rotation={[0, productFrontRest.rotationY, 0]}
        >
          <SceneEngineContext.Provider value={productContextValue}>
            <ProductSceneV2
              assetsRef={productAssetsRef}
              ready={productReady}
              alignRef={alignRef}
              roomVisible={productRoomVisible}
              lightsActiveRef={lightsActiveRef}
              phaseRef={productPhaseRef}
              activeRef={productOnScreenRef}
              restPosition={productFrontRest.position}
              restRotationY={productFrontRest.rotationY}
              cameraPosition={DEFAULT_CAMERA.position}
              cameraTarget={DEFAULT_CAMERA.target}
              nudge={productNudge}
              finalNudgeZ={productFinalNudgeZ}
              onRevealedChange={onProductRevealedChange}
              fogNoise={sharedMaps?.fogNoise}
              showerFogRef={showerFogRef}
            />
          </SceneEngineContext.Provider>
        </group>
      )}
      {/* Fixed in front of the (fixed) camera at all times — the FRONT
          slot's own resting transform, see restFrame — independent of the
          swing carousel's per-scene motion above. Only its flavor and
          rotation change, driven by progressRef (see swingCarousel.js), until
          the scene-to-product handoff's flightOverrideRef takes over (see
          BottleRigV2's own comment) and eventually hides it for good once the
          bottle has landed on its resting spot in product's room. */}
      {/* Hidden for the whole product flythrough: this rig is parked at the
          FRONT slot's standoff, which is exactly where the alignment solve
          puts the carousel camera — i.e. INSIDE product's room. Left on, it
          would hang in the middle of the shot the moment the flythrough
          camera takes over. Only the flythrough phase is gated, not the
          swing-in, so the bottle still reads normally right up to the
          hand-off (by which point flightOverrideRef.hidden has already taken
          it off screen anyway). */}
      <HideWhile hiddenRef={productOnScreenRef}>
        {/* Same Bottle.blend-derived studio rig as the standalone
            /bottle-studio page (see BottleStudioLights), parked on the
            bottle's actual GEOMETRIC CENTRE in world space — which is what
            /bottle-studio puts at this rig's origin, by translating the model
            there instead (see BottleStudioSceneV2's recenterRef). Z is the
            bottle group's own resting world Z (BottleRigV2 adds
            BOTTLE_OFFSET_Z straight to world Z, not as a locally-rotated
            offset, so this matches it exactly); Y lifts the rig off that
            group's origin onto the model's centre — see
            BOTTLE_CENTER_OFFSET_Y for why they are not the same point. */}
        <BottleStudioLights
          enabled
          position={[
            0,
            BOTTLE_CENTER_OFFSET_Y,
            -CIRCLE_RADIUS + BOTTLE_OFFSET_Z,
          ]}
          // Rig was tuned against /bottle-studio's 0.2 exposure — this Canvas
          // runs at CANVAS_EXPOSURE, so every light rescales to hold the same
          // authored look here (see scenes-v2/studioExposure.js).
          canvasExposure={CANVAS_EXPOSURE}
          // Per-scene accent colour (see studioSceneTints.js): the rig's
          // overhead magenta disk light cross-fades to the front scene's own
          // accent as the carousel swings, so the bottle's rim picks up the
          // room it's standing in instead of wearing the same magenta through
          // a green room and a red one. Read per-frame off progressRef.frontIndex — the same
          // value ActiveSceneTracker watches — rather than plumbed down as
          // state, so a scene change re-tints without re-rendering the Canvas.
          sceneIds={SCENE_IDS}
          progressRef={progressRef}
          // Wireframe gizmos for all 11 lights, so the rig can actually be
          // seen and dialled in against the bottle here the way it can on
          // /bottle-studio (which passes showHelpers outright). Off by
          // default even in dev — the "Bottle Studio Lights > Show helpers"
          // checkbox in the debug panel still toggles it on at runtime when
          // actually dialling in lights.
          showHelpers={false}
        />
        <BottleRigV2
          scenes={SCENES}
          enabled={enabled}
          position={getRestFrame(faceRotations, 0).position}
          rotationY={getRestFrame(faceRotations, 0).rotationY}
          progressRef={progressRef}
          flightOverrideRef={flightOverrideRef}
          groupRefOut={bottleGroupRef}
          // The bottle's OWN materials need the identical exposure rescale
          // its lights just got — its body is a pure metal, so its whole
          // appearance is the environment reflection that scale governs (see
          // scenes-v2/studioExposure.js).
          canvasExposure={CANVAS_EXPOSURE}
        />
      </HideWhile>
      {minimapEnabled && (
        <>
          <DebugRing radius={CIRCLE_RADIUS} />
          <MainCameraHelper camera={camera} />
        </>
      )}
      {/* No postFxEnabled gate any more — SceneRenderDriver carries no
          bloom/composer cost to hold off, just the render loop + engine
          tick every scene actually needs to not be frozen (see its own
          comment). */}
      <SceneRenderDriver
        minimapEnabled={minimapEnabled}
        minimapCamera={minimapCamera}
        progressRef={progressRef}
        productActiveRef={productOnScreenRef}
        productRevealed={productRevealed}
        handoffActiveRef={handoffActiveRef}
      />
    </>
  );
}

const DEFAULT_FOV = 45;
// The camera widens to this while a carousel step sweeps, then eases back to
// DEFAULT_FOV before the step lands — see useSwingCarousel's
// applyTransitionFov for the curve. GUI-tunable at runtime ("Transition FOV"),
// this is just its starting value; set it equal to DEFAULT_FOV to switch the
// whole effect off.
const DEFAULT_TRANSITION_FOV = 42;
// Where in the step the widened FOV starts easing back, as a fraction of the
// step: it peaks here and is back at DEFAULT_FOV exactly at t=1, so 0.65
// means "pull back in over the last third of the sweep". Not GUI-exposed —
// this is the shape of the move, not a per-look dial.
const TRANSITION_FOV_RETURN_AT = 0.65;

// `gui` (optional) is a page-shared lil-gui panel (see useDebugGui /
// HomeV2Page, which creates one instance and hands it to both SceneV2 and
// ProductV2) — when supplied, this scene's controls live in their own
// "Scene V2" sub-folder on it instead of a second floating panel. Left
// undefined (e.g. the standalone /scene2 route in App.jsx), SceneV2 falls
// back to creating and owning its own panel, exactly as before.
export default function SceneV2({
  gui: sharedGui,
  // Optional: notified with the carousel's own frontIndex (index into
  // SCENES, see SCENE_COUNT) every time it changes — lets a parent (e.g.
  // HomeV2Page, gating when Product mounts) track which scene is resting
  // at FRONT without owning that state itself.
  onActiveSceneChange,
  // Whether the one-shot scene-to-product handoff (the bottle flying into
  // product's room, the camera flythrough, the "+" hotspots — see
  // useSceneToProductHandoff) lives past the carousel's last scene at all.
  //
  // Off, this section is JUST the swing carousel: scrolling forward from the
  // last scene releases the wheel and carries on down the page, the product
  // room/bottle assets are never even fetched (see useProductAssets), and
  // the section reserves no scroll room for any of it.
  productEnabled = true,
  // Extra vh of scroll room added to the END of this section, past
  // everything it actually animates, purely so its `position: sticky` canvas
  // is still pinned for that much longer. Pages that hand this section off
  // via a CloudTransition need it: that wipe arms one viewport before its
  // boundary marker, and a sticky box un-sticks one viewport before its own
  // container ends — identical positions unless the marker is lifted off the
  // section's end, which is what this room pays for. See HomeV3Page.
  trailingHoldVh = 0,
  // Whether this section shows its own "scroll to explore" cue, centered at
  // the bottom of the pinned canvas. Opt-in: only HomeV3Page's carousel-only
  // variant wants it — pages where the carousel is one leg of a longer
  // sequence (HomeV2Page, /scene2) never had one.
  scrollCue = false,
} = {}) {
  const [enabled, setEnabled] = useState(() =>
    Object.fromEntries(SCENES.map((s) => [s.id, true])),
  );
  const [scenePanel, setScenePanel] = useState(null);
  // Product's own debug folder ("Product V2") — a SIBLING of "Scene V2" on
  // the same base panel, not nested inside it, mirroring the separate
  // top-level folder the old standalone Product.v2.jsx wrapper used to
  // build for itself. Built in the same effect as "Scene V2" below since
  // both need the same `basePanel`.
  const [productPanel, setProductPanel] = useState(null);
  const ownGui = useDebugGui(sharedGui ? null : "Scene V2 Tweaks");
  const basePanel = sharedGui ?? ownGui;
  const [engine] = useState(() => createSceneEngine());
  const [fov, setFov] = useState(DEFAULT_FOV);
  const [transitionFov, setTransitionFov] = useState(DEFAULT_TRANSITION_FOV);
  const [minimapEnabled, setMinimapEnabled] = useState(false);
  const [statsEnabled, setStatsEnabled] = useState(false);
  // Cursor parallax truck on the camera (see CameraRig) — off by default,
  // GUI-toggleable via "Cursor Parallax" below so it can be switched on/off
  // at will without a code change.
  const [parallaxEnabled, setParallaxEnabled] = useState(false);
  const [debugCameraPosition, setDebugCameraPosition] = useState(() => ({
    x: DEFAULT_CAMERA.position[0],
    y: DEFAULT_CAMERA.position[1],
    z: DEFAULT_CAMERA.position[2],
  }));
  // Per-scene "face the front slot" correction (radians) — was a fixed
  // Math.PI (180deg) per scene, now GUI-tunable, see DEFAULT_EXTRA_Y_ROTATIONS
  // and the "Model Rotation" GUI folder below.
  const [extraYRotations, setExtraYRotations] = useState(
    DEFAULT_EXTRA_Y_ROTATIONS,
  );
  const [sweepAngleDeg, setSweepAngleDeg] = useState(DEFAULT_SWEEP_ANGLE_DEG);
  const [lightRevealAngleDeg, setLightRevealAngleDeg] = useState(
    DEFAULT_LIGHT_REVEAL_ANGLE_DEG,
  );
  const [lightUp, setLightUp] = useState(DEFAULT_LIGHT_UP);
  // Product's own static facing — see DEFAULT_PRODUCT_RING_ROTATION_DEG. Was
  // a swing-path knob (which way the room rotated through on its way round
  // the ring); product no longer swings in (see useSceneToProductHandoff),
  // so this is now purely which way the room faces at rest. Where it comes
  // to rest is still solved for (see useProductAlignment), not set here.
  const [productFacingDeg, setProductFacingDeg] = useState(
    DEFAULT_PRODUCT_RING_ROTATION_DEG,
  );
  // Post-solve nudge in the fixed camera's own local space — see
  // useProductAlignment's own comment for why this exists (every scene
  // shares one camera fov, so an exact pose match doesn't guarantee a
  // well-framed rest shot) and the tradeoff it makes (a non-zero value
  // reintroduces a small pop at the moment the flythrough camera later
  // takes over).
  const [productNudge, setProductNudge] = useState(DEFAULT_PRODUCT_NUDGE);
  const [productFinalNudgeZ, setProductFinalNudgeZ] = useState(
    DEFAULT_PRODUCT_FINAL_NUDGE_Z,
  );

  // `basePanel` is either this scene's own dedicated panel (ownGui, created
  // by useDebugGui above) or the page-shared one passed in via `sharedGui` —
  // either way it doesn't exist yet on the very first render (useDebugGui's
  // own effect hasn't run, or the parent hasn't created/passed its shared
  // panel down yet), so this effect is keyed on it rather than running once
  // on mount. When sharing, everything below is built under a dedicated
  // "Scene V2" sub-folder so it can't collide with another section's (e.g.
  // ProductV2's) folder names on the same shared panel; standalone, basePanel
  // IS already this scene's own panel, so it's used directly as the root.
  useEffect(() => {
    if (!basePanel) return undefined;
    const root = sharedGui ? basePanel.addFolder("Scene V2") : basePanel;

    const scenesFolder = root.addFolder("Scenes");
    SCENES.forEach((scene) => {
      scenesFolder
        .add({ [scene.id]: true }, scene.id)
        .name(scene.label)
        .onChange((v) => setEnabled((prev) => ({ ...prev, [scene.id]: v })));
    });
    root
      .add({ fov: DEFAULT_FOV }, "fov", 10, 120, 1)
      .name("Camera FOV")
      .onChange((v) => setFov(v));
    root
      .add(
        { transitionFov: DEFAULT_TRANSITION_FOV },
        "transitionFov",
        10,
        120,
        1,
      )
      .name("Transition FOV")
      .onChange((v) => setTransitionFov(v));
    root
      .add({ minimap: true }, "minimap")
      .name("Debug Minimap")
      .onChange((v) => setMinimapEnabled(v));
    root
      .add({ parallax: false }, "parallax")
      .name("Cursor Parallax")
      .onChange((v) => setParallaxEnabled(v));
    root
      .add({ stats: false }, "stats")
      .name("Show FPS Stats")
      .onChange((v) => setStatsEnabled(v));
    root
      .add({ sweepAngle: DEFAULT_SWEEP_ANGLE_DEG }, "sweepAngle", 10, 180, 1)
      .name("Sweep Angle")
      .onChange((v) => setSweepAngleDeg(v));
    root
      .add(
        { lightRevealAngle: DEFAULT_LIGHT_REVEAL_ANGLE_DEG },
        "lightRevealAngle",
        1,
        180,
        1,
      )
      .name("Light Reveal Angle")
      .onChange((v) => setLightRevealAngleDeg(v));

    const rotationFolder = root.addFolder("Model Rotation");
    const rotationSettings = Object.fromEntries(
      SCENES.map((s) => [
        s.id,
        THREE.MathUtils.radToDeg(DEFAULT_EXTRA_Y_ROTATIONS[s.id]),
      ]),
    );
    SCENES.forEach((scene) => {
      rotationFolder
        .add(rotationSettings, scene.id, 0, 360, 1)
        .name(scene.label)
        .onChange((v) =>
          setExtraYRotations((prev) => ({
            ...prev,
            [scene.id]: THREE.MathUtils.degToRad(v),
          })),
        );
    });

    // Shape of the light-up reveal on the video planes — see VideoPlaneV2's
    // LIGHT_UP_FRAGMENT for what each one does to the curve. Global rather
    // than per-scene: it's one lighting gesture the whole carousel shares.
    const lightFolder = root.addFolder("Light Up");
    const lightSettings = { ...DEFAULT_LIGHT_UP };
    const onLightChange = () => setLightUp({ ...lightSettings });
    lightFolder
      .add(lightSettings, "startAt", 0, 0.95, 0.01)
      .name("Start At (swing)")
      .onChange(onLightChange);
    lightFolder
      .add(lightSettings, "clipStartAt", 0, 0.95, 0.01)
      .name("Clip Start (swing)")
      .onChange(onLightChange);
    lightFolder
      .add(lightSettings, "softness", 0.02, 1, 0.01)
      .name("Edge Softness")
      .onChange(onLightChange);
    lightFolder
      .add(lightSettings, "boost", 0, 2, 0.01)
      .name("Ignition Boost")
      .onChange(onLightChange);
    lightFolder
      .add(lightSettings, "floor", 0, 1, 0.01)
      .name("Off-State Level")
      .onChange(onLightChange);
    // Take the scene currently resting at FRONT off the scroll and put its
    // reveal on the toggle below, so the curve can be judged (and the two
    // sliders above dialed in) without scrolling a scene past the camera for
    // every attempt. Only that one scene is affected; the rest keep tracking
    // the carousel.
    const previewControllers = [
      lightFolder
        .add(lightSettings, "preview")
        .name("Preview Active Scene")
        .onChange(onLightChange),
      lightFolder
        .add(lightSettings, "previewOn")
        .name("- Lights On")
        .onChange(onLightChange),
    ];

    const posFolder = root.addFolder("Camera Position");
    const posSettings = {
      x: DEFAULT_CAMERA.position[0],
      y: DEFAULT_CAMERA.position[1],
      z: DEFAULT_CAMERA.position[2],
    };
    const onPosChange = () =>
      setDebugCameraPosition({
        x: posSettings.x,
        y: posSettings.y,
        z: posSettings.z,
      });
    posFolder.add(posSettings, "x", -40, 40, 0.1).onChange(onPosChange);
    posFolder.add(posSettings, "y", -20, 40, 0.1).onChange(onPosChange);
    posFolder.add(posSettings, "z", -40, 40, 0.1).onChange(onPosChange);

    // Dumps every control currently under `root` — the five scenes' own
    // folders (Fog/Sea/Droplet/Glass/etc., added directly to this same
    // panel by each scene component via SceneEngineContext, see
    // SceneContents/contextValue above) — as one JSON file via lil-gui's own save() (walks
    // controllers/folders recursively, keyed by the `.name()`/folder title
    // each was given above). Whatever's dialed in at click time becomes the
    // new starting point: overwrite scenes-v2/scene-v2-settings.json with
    // the downloaded file and every value in it becomes the app's initial
    // value on next load (see the sceneV2Settings import above and its
    // root.load()/applyFolderSettings() call sites) — no DEFAULT_* editing
    // needed.
    root
      .addFolder("Export")
      .add(
        {
          exportSettings: () => {
            const snapshot = root.save();
            const json = JSON.stringify(snapshot, null, 2);
            console.log("[Scene V2] Exported settings:", snapshot);
            const blob = new Blob([json], { type: "application/json" });
            const url = URL.createObjectURL(blob);
            const link = document.createElement("a");
            link.href = url;
            link.download = `scene-v2-settings-${new Date()
              .toISOString()
              .replace(/[:.]/g, "-")}.json`;
            link.click();
            URL.revokeObjectURL(url);
          },
        },
        "exportSettings",
      )
      .name("Export Settings (JSON)");

    // Applies scene-v2-settings.json over the DEFAULT_* values above, for
    // every folder that already exists at this point (everything built
    // synchronously in this effect: Scenes, Camera FOV/Transition FOV/
    // Debug Minimap/Show FPS Stats/Sweep Angle, Model Rotation, Camera
    // Position). Each scene's own material folders
    // (Fog/Sea/Droplet/...) don't exist yet at this point — they're added
    // once that scene's assets finish loading — so each scene applies its
    // own slice itself via applyFolderSettings (see SceneOneV2.jsx etc.).
    root.load(sceneV2Settings);
    // Whatever the exported settings say, the debug preview starts off: it's
    // a testing override, and a snapshot taken with it on would otherwise
    // load as a permanently dark front scene. setValue fires the same
    // onChange as a click, so the React state follows.
    previewControllers.forEach((controller) => controller.setValue(false));

    root.open();

    // Product's own folder — a sibling of "Scene V2" directly on basePanel,
    // built the same way the old standalone Product.v2.jsx wrapper built its
    // own top-level panel, just sharing this one instead of floating a
    // second panel. Its own sub-folders (Bathroom bottle light, Bottle
    // Reveal, Selective Blur, ...) are added by ProductLights/useBottleReveal/
    // SelectiveBlurRenderer themselves once product's assets finish loading,
    // same lazy pattern each SCENES component already uses on `root`.
    const productRoot = basePanel.addFolder("Product V2");
    productRoot.open();

    // Where product's room comes to REST is solved for (see
    // useProductAlignment), not hand-placed — so the arrival pose and the
    // flythrough's own frame-0 pose are the same pose by construction, which
    // is the basis of the seamless camera switch. "Facing" only picks which
    // way the room is oriented at that static rest pose (it no longer swings
    // in, see useSceneToProductHandoff), never where it lands. "Nudge X/Y/Z"
    // is the one deliberate exception: it offsets the solved position IN THE
    // CAMERA'S OWN SPACE (right/up/closer, not world axes), trading away some
    // of that seamlessness for a better-framed rest shot — see
    // useProductAlignment's own comment for why that tradeoff exists and
    // why camera-space (not world-space) is what keeps a nudge from making
    // the subject swing off-center as it's pulled closer.
    const placementFolder = productRoot.addFolder("Placement");
    const placementSettings = {
      facing: DEFAULT_PRODUCT_RING_ROTATION_DEG,
      nudgeX: DEFAULT_PRODUCT_NUDGE.x,
      nudgeY: DEFAULT_PRODUCT_NUDGE.y,
      nudgeZ: DEFAULT_PRODUCT_NUDGE.z,
      finalNudgeZ: DEFAULT_PRODUCT_FINAL_NUDGE_Z,
    };
    placementFolder
      .add(placementSettings, "facing", 0, 360, 1)
      .name("Room Facing")
      .onChange((v) => setProductFacingDeg(v));
    const onNudgeChange = () =>
      setProductNudge({
        x: placementSettings.nudgeX,
        y: placementSettings.nudgeY,
        z: placementSettings.nudgeZ,
      });
    placementFolder
      .add(placementSettings, "nudgeX", -10, 10, 0.05)
      .name("Nudge Right (+)")
      .onChange(onNudgeChange);
    placementFolder
      .add(placementSettings, "nudgeY", -10, 10, 0.05)
      .name("Nudge Up (+)")
      .onChange(onNudgeChange);
    placementFolder
      .add(placementSettings, "nudgeZ", -10, 10, 0.05)
      .name("Distance (+closer)")
      .onChange(onNudgeChange);
    placementFolder
      .add(placementSettings, "finalNudgeZ", -10, 40, 0.05)
      .name("Final distance (+closer)")
      .onChange((v) => setProductFinalNudgeZ(v));

    // lil-gui is an external, imperative DOM system — this effect's whole
    // job is to synchronize a fresh folder/panel into React state so context
    // can hand it to scene components. There's no way to do that without a
    // setState call inside the effect that created it.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setScenePanel(root);

    setProductPanel(productRoot);
    return () => {
      // Only this scene's own sub-folder is ours to tear down when sharing —
      // the shared panel itself outlives this component (owned by whoever
      // created it, e.g. HomeV2Page). Standalone, basePanel/root IS the owned
      // panel, and useDebugGui's own effect already destroys it.
      if (sharedGui) root.destroy();
      setScenePanel((current) => (current === root ? null : current));
      productRoot.destroy();
      setProductPanel((current) => (current === productRoot ? null : current));
    };
  }, [basePanel, sharedGui]);

  const contextValue = useMemo(
    () => ({ engine, gui: scenePanel, settings: sceneV2Settings }),
    [engine, scenePanel],
  );
  const sectionRef = useRef(null);
  // This Canvas is desktop-only in the normal page flow (HomeV3Page only
  // mounts it past the `lg` breakpoint), but the standalone /scene2 route
  // (see App.jsx) renders it directly with no such gate — so a phone hitting
  // that route still needs the same dpr/AA break a "real" mobile viewport
  // would get. Reused rather than re-derived: same `lg` breakpoint everything
  // else on the page switches WebGL layers on.
  const isDesktop = useIsDesktop();
  const { handoff, manager } = usePreloader();
  // Under PreloaderV2, don't mount the Canvas until the overlay is handing
  // off. Video planes / bottle GLBs / GPU warmup were competing with the
  // hero reel and holding first paint. The section still reserves its
  // scroll height; WebGL starts at handoff, which is a full autoplay +
  // scroll before this canvas is on screen. /scene2 has no manager, so
  // the canvas mounts immediately.
  const canvasReady = !manager || handoff;

  // R3F's default frameloop ("always") renders forever once mounted, with no
  // regard for whether .scene-v2 is anywhere near the viewport — so every
  // scroll past this section (into ProductShelf/KeyHighlights/VideoHero/
  // Footer) was still paying for 5 scenes' worth of materials and water-
  // reflection passes (see engine.js, ticked every frame by
  // SceneRenderDriver), every single frame, competing with whatever's
  // actually on screen for GPU/main-thread time — see FooterScene's own
  // IntersectionObserver gate for the
  // same class of bug it already had to fix once. rootMargin gives it a full
  // viewport of lead time each way so the very first frame after crossing
  // back in is already correct — nothing here depends on wall-clock time
  // (see swingCarousel.js's own comment), it's all driven off live scroll
  // position, so pausing/resuming the loop is safe with no catch-up frame.
  const [nearViewport, setNearViewport] = useState(false);
  // Tighter than nearViewport: that's 100% rootMargin so materials/shaders
  // are already compiling when you arrive. Videos must NOT use that window —
  // it marks this section "near" from the hero (and still at the footer).
  const [sectionInView, setSectionInView] = useState(false);
  useEffect(() => {
    const el = sectionRef.current;
    if (!el || typeof IntersectionObserver === "undefined") return undefined;
    const warmup = new IntersectionObserver(
      ([entry]) => setNearViewport(entry.isIntersecting),
      { rootMargin: "100% 0px" },
    );
    const onScreen = new IntersectionObserver(
      ([entry]) => {
        // Hairline overlap at the Seawave/Scene seam (section top sitting
        // on the viewport bottom edge) is enough for isIntersecting, and
        // that was starting the bathroom loop while Seawave still owned
        // the frame. Require a few pixels of real overlap.
        setSectionInView(
          entry.isIntersecting && entry.intersectionRect.height > 8,
        );
      },
      { rootMargin: "0px", threshold: [0, 0.01] },
    );
    warmup.observe(el);
    onScreen.observe(el);
    return () => {
      warmup.disconnect();
      onScreen.disconnect();
    };
  }, []);

  // Handed down into useSwingCarousel so it can stop()/start() Lenis itself
  // — see that hook's own comment for why that's necessary now that
  // .scene-v2 is a real in-flow sticky section rather than a fixed overlay.
  const lenis = useLenis();

  // Which scene is currently resting at FRONT — drives the bottom-of-screen
  // caption (see SceneCaption) below. Kept as plain state up here (outside
  // the Canvas) rather than read directly from progressRef, since this
  // overlay is regular DOM, not R3F — see ActiveSceneTracker.
  const [activeSceneIndex, setActiveSceneIndex] = useState(0);
  const handleActiveSceneChange = useCallback(
    (idx) => {
      setActiveSceneIndex(idx);
      onActiveSceneChange?.(idx);
    },
    [onActiveSceneChange],
  );

  // Whether a bottle is currently flown out — drives the DOM product overlay
  // below. Plain state up here (outside the Canvas) for the same reason
  // activeSceneIndex is: that overlay is regular DOM, not R3F.
  const [productRevealed, setProductRevealed] = useState(false);
  // Which node was revealed (see useBottleReveal's onRevealedChange), so the
  // overlay can show THAT bottle's own product data instead of a fixed one.
  // Only ever updated on reveal, not on return — the overlay's own fade-out
  // reads whatever this was last set to, so it fades out on the same card it
  // faded in on rather than snapping to nothing first.
  const [productRevealedNode, setProductRevealedNode] = useState(null);
  const handleProductRevealedChange = useCallback((revealed, nodeName) => {
    setProductRevealed((current) =>
      current === revealed ? current : revealed,
    );
    if (revealed) setProductRevealedNode(nodeName);
  }, []);

  // Whether the scene-to-product handoff currently owns the screen — true
  // from the moment the fog starts rising on the way OUT of the carousel
  // until the reverse wipe has fully landed back on it (see
  // useSceneToProductHandoff's own comment on handoffActiveRef, which this
  // mirrors — deliberately NOT the same thing as SceneContents' own inner
  // productActiveRef, which only covers whether product's range is
  // currently entered (see useProductPhase/useProductAutoZoom), not the
  // transition either side of it). Drives SceneCaption's own fade below:
  // the carousel's heading/paragraph has no business being on screen while
  // product owns the frame.
  const [handoffActive, setHandoffActive] = useState(false);

  return (
    // Gives the page real, normal-flow scroll distance for the swing
    // carousel, the one-shot scene-to-product handoff, AND the product
    // flythrough that all live inside this same section — doubles as the
    // sticky containing block for `.scene-v2` below, see its own CSS
    // comment. (SCENES.length - 1) transitions of 50vh each (see
    // swingCarousel.js's STEP_VH_FRACTION) cycles through every scene 0-4;
    // the wheel-lock releases right there (see swingCarousel.js's
    // maxStep/inRange) — continuing to scroll forward from that rest
    // triggers useSceneToProductHandoff's own one-shot auto-scroll
    // (HANDOFF_SCROLL_VH) straight into PRODUCT_RANGE_VH, with no extra dead
    // zone. PRODUCT_RANGE_VH is now PURELY a linger beat (see constants.js):
    // the room's zoom plays itself on a timer with scroll locked, so by the
    // time this range is scrollable at all the shot has already landed and
    // the "+" hotspots are up — this is just how long it stays pinned to be
    // read and clicked before KeyHighlightsV2/VideoHeroV2 scroll up over it.
    // It used to be ~4x longer, carrying a 300vh camera-scrub range that
    // nothing reads any more; that surplus was scroll you had to grind
    // through before the section would release. STICKY_RELEASE_VH is then
    // added on top so the canvas stays pinned for the whole combined range —
    // see its own comment.
    <div
      ref={sectionRef}
      className="scene-v2__scroll-section"
      style={{
        height: `${
          (SCENES.length - 1) * STEP_VH_FRACTION * 100 +
          (productEnabled ? HANDOFF_SCROLL_VH + PRODUCT_RANGE_VH : 0) +
          STICKY_RELEASE_VH +
          trailingHoldVh
        }vh`,
      }}
    >
      {/* See pageSections.js's "shop" entry / Scene.v2.css's own comment —
          PageProgress reads this element's document position for its "Shop"
          rail label. Same offset useProductPhase's carouselOwnedVh uses, so
          it lands exactly on the carousel -> product hold-zone handoff. */}
      {productEnabled && (
        <div
          className="scene-v2__shop-marker"
          style={{
            top: `${(SCENES.length - 1) * STEP_VH_FRACTION * 100 + HANDOFF_SCROLL_VH}vh`,
          }}
          aria-hidden="true"
        />
      )}
      <div className="scene-v2">
        {canvasReady && (
        <Canvas
          className="scene-v2__canvas"
          // 'always' ONLY while the section is genuinely on screen. The
          // warm-up band (nearViewport) runs 'demand' instead, so it compiles
          // via WarmupFrames' few invalidate() calls rather than a persistent
          // 60fps loop competing with whatever actually owns the frame — see
          // WarmupFrames. Everything in here is driven off live scroll
          // position, never wall-clock, so resuming needs no catch-up frame.
          frameloop={
            sectionInView ? "always" : nearViewport ? "demand" : "never"
          }
          // Capped at 2, not left unbounded — every full-screen pass here
          // (video planes + water reflections + N8AO + bloom) scales with
          // pixel count, so an uncapped dpr (3 on some phones) would be
          // 9x the fill of dpr=1. This used to be pinned to 1 outright to
          // dodge a 500ms+ hitch on the first swing, but that made the
          // bottle label's small print bilinear-upscaled to a blur on every
          // retina display — re-measure swing-in frame time if this needs
          // tuning further.
          // On a sub-`lg` viewport (only reachable here via the standalone
          // /scene2 route — HomeV3Page never mounts this Canvas on mobile)
          // dpr is pinned to 1: this section is 5 full-bleed video-plane
          // shaders plus water reflections, and doubling that fill rate is
          // what a phone GPU can least afford.
          dpr={isDesktop ? [1, 2] : 1}
          camera={{
            fov: DEFAULT_FOV,
            near: 0.1,
            far: 1000,
            position: DEFAULT_CAMERA.position,
          }}
          // alpha:false — .scene-v2's own CSS background is solid #000 and
          // the THREE scene below always paints an opaque background color
          // (see <color attach="background"> a few lines down), so nothing
          // behind this canvas is ever visible. alpha:true was forcing the
          // browser to composite this canvas as transparent every frame
          // (extra blend work, and disables some fast paths on Chrome/
          // ANGLE) for a page underneath that can never show through.
          // powerPreference nudges hybrid-GPU laptops toward the discrete
          // GPU instead of silently defaulting to integrated graphics,
          // which alone can be a 2-3x frame-time difference on that class
          // of hardware.
          // antialias:true — SceneRenderDriver's gl.render() draws straight
          // into this canvas now (PostFXV2's SMAA pass is gone, see that
          // function's comment), so unlike before, WebGL's own MSAA DOES
          // see this canvas's edges. Without it the bottle silhouette's
          // rounded cap and long diagonals rasterize jagged/banded.
          // Off on a sub-`lg` viewport (see the dpr comment above): MSAA's
          // multisample cost stacks with the full-bleed video-plane shaders,
          // and dpr is already down to 1 there so the jaggies it would
          // otherwise catch are the least of that budget's problems.
          gl={{
            antialias: isDesktop,
            alpha: false,
            powerPreference: "high-performance",
          }}
          onCreated={({ gl }) => {
            gl.outputColorSpace = THREE.SRGBColorSpace;
            gl.toneMapping = THREE.ACESFilmicToneMapping;
            gl.toneMappingExposure = CANVAS_EXPOSURE;
          }}
        >
          <color attach="background" args={[0x000000]} />
          {statsEnabled && <Stats />}
          <WarmupFrames active={nearViewport && !sectionInView} />
          <SceneEngineContext.Provider value={contextValue}>
            <SceneContents
              enabled={enabled}
              sectionInView={sectionInView}
              sectionRef={sectionRef}
              fov={fov}
              transitionFov={transitionFov}
              minimapEnabled={minimapEnabled}
              debugCameraPosition={debugCameraPosition}
              parallaxEnabled={parallaxEnabled}
              extraYRotations={extraYRotations}
              sweepAngle={THREE.MathUtils.degToRad(sweepAngleDeg)}
              lightRevealAngle={THREE.MathUtils.degToRad(lightRevealAngleDeg)}
              onActiveSceneChange={handleActiveSceneChange}
              lenis={lenis}
              lightUp={lightUp}
              productGui={productPanel}
              productFacing={THREE.MathUtils.degToRad(productFacingDeg)}
              productNudge={productNudge}
              productFinalNudgeZ={productFinalNudgeZ}
              productRevealed={productRevealed}
              onProductRevealedChange={handleProductRevealedChange}
              onProductActiveChange={setHandoffActive}
              productEnabled={productEnabled}
            />
          </SceneEngineContext.Provider>
        </Canvas>
        )}

        {/* Wraps SceneCaption rather than touching it directly — that
            component's own opacity is already busy crossfading between
            scenes (see its own CaptionPair enter/exit/idle phases), so this
            layers a coarser "hide the whole block" fade on top for the
            handoff, driven by handoffActive, instead of teaching that
            per-scene logic about product at all. */}
        <div
          className="pointer-events-none transition-opacity duration-500 ease-out"
          style={{ opacity: handoffActive ? 0 : 1 }}
        >
          <SceneCaption sceneId={SCENES[activeSceneIndex]?.id} />
        </div>

        {/* Centered scroll cue over the carousel — the hero's own cue (see
            IntroHeroV3) doesn't reach this far down, and the canvas has no
            scroll nudge of its own. Absolutely positioned inside this
            sticky, viewport-filling box rather than fixed to the page, so
            the pin itself is what carries it on and off screen: no
            enter/exit bookkeeping, and nothing left over the sections
            either side of this one. Faded on handoffActive for the same
            reason SceneCaption above is — the cue has no business nudging
            you to scroll while product owns the frame. */}
        {scrollCue && (
          <div
            className="transition-opacity duration-500 ease-out"
            style={{ opacity: handoffActive ? 0 : 1 }}
          >
            <HeroScrollCue variant="center" fadeOutAt={0} />
          </div>
        )}

        {/* The DOM half of the bottle reveal (product title art, quote,
            details card) — a sibling of the Canvas rather than a child, the
            same way SceneCaption is, since it's ordinary React DOM. Kept
            mounted at all times and faded via opacity so its own
            transition can play in both directions. */}
        {productEnabled && (
          <ProductOverlayV2
            revealed={productRevealed}
            nodeName={productRevealedNode}
          />
        )}

        {/* Purely cosmetic frame around the minimap's WebGL inset (drawn
            straight into the canvas by PostFXV2 via scissor/viewport) — same
            size/offset as MINIMAP_SIZE/MINIMAP_PAD so it lines up exactly.
            pointer-events: none so it never intercepts the carousel's own
            window-level wheel handling. */}
        {minimapEnabled && (
          <div className="scene-v2__minimap-frame">
            <span className="scene-v2__minimap-label">Debug: top-down</span>
          </div>
        )}

        <Loader />
      </div>
    </div>
  );
}
